data:
    data_url: https://drive.google.com/file/d/1CApw-tk_ifrbDR4ZQ-dQz5vqH016P3UM/view?usp=drive_link
    data_path: "/root/playgrounds/Celebrity_Recognition/data/Assignment - Celebrity Recognition.zip"